dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: decide-alf-practica7
  strategy: git
  api_key:
    secure: cx6Va2pfJMe+6PR3wFbxWQCmZpRC6oRmxS4oXy3RPJhfy6h7B5owMZUanOdtpEjd+OJrSjtLf5ELiC2HbMCVVJ4kw9IWg/jlB/VhR6F4cyuGyeguus2IE5WnlCyvfws18HuI+YbPIe4b+nL93Ws3Fgrj3IEfN2DY7fOnbTju32mZr7FYcrQ71WDmP7OhspY6jRcgcrKN/F0hXSRPlh+kxhpllCw/pF5AjI4EnrXJ0/4YvjD4KODRVoAT5FOz4bqQ9K9f5o+Gs3d1+kHN189LanRDP7lLCUJQu8dXvsWVFFQqSzgm0s9RH12cnq2LnvReoQB/XpM8INMmfLLfkFk75QY9uq04jgxcgGuOsrrIvYqCWx78m647LQY1Mbm4wZUj6VMS77KC3tf+k3fa6U8TknaVUoJpg1C9OZLdh5ANK4eLY/73ruIJwu9aUWS6PZVEop1U7nP4nAyPqaJrX1q6NX3jKL2YQRjS4ioZ3yo9aNkL9uoHZs+U7bX8X5vgKwxVR9hq/dlY0XI77Muk8kwkXw4l/DD1HHJ5Lq75HajTl7KrCBFSpizJbrSE6OogUsiscL5ulc3SHGyseKD7BPpTwSh1p3lBcJd07UVZBYrIP1ydbRNQacRNYGFelQ3dNTkC8q/ZL0CxzpawvWVw3aQmQPr/zPMJYJYzHZT8+wICNlo=
